export const FETCH_STOCK_LIST_REQUEST = 'FETCH_STOCK_LIST_REQUEST';
export const FETCH_STOCK_LIST_SUCCESS = 'FETCH_STOCK_LIST_SUCCESS';
export const FETCH_STOCK_LIST_FAIL = 'FETCH_STOCK_LIST_FAIL';

export const CREATE_ORDER_REQUEST = 'CREATE_ORDER_REQUEST';
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS';
export const CREATE_ORDER_FAIL = 'CREATE_ORDER_FAIL';